/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaTransport
 * Method:    nParseSessions
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaTransport_nParseSessions
  (JNIEnv *, jclass);

/*
 * Class:     by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession
 * Method:    nSwitchToNext
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession_nSwitchToNext
  (JNIEnv *, jclass, jint);

/*
 * Class:     by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession
 * Method:    nSwitchToPrevious
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession_nSwitchToPrevious
  (JNIEnv *, jclass, jint);

/*
 * Class:     by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession
 * Method:    nPlay
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession_nPlay
  (JNIEnv *, jclass, jint);

/*
 * Class:     by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession
 * Method:    nPause
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession_nPause
  (JNIEnv *, jclass, jint);

/*
 * Class:     by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession
 * Method:    nTogglePlay
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession_nTogglePlay
  (JNIEnv *, jclass, jint);

/*
 * Class:     by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession
 * Method:    nStop
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_by_bonenaut7_mediatransport4j_impl_windows_WindowsMediaSession_nStop
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif